name: Deploy to Kubernetes
on:
  workflow_run:
    workflows: ["docker-build-push_CI-pipline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-python-deployment
  labels:
    app: helloworld-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-python
  template:
    metadata:
      labels:
        app: helloworld-python
    spec:
      containers:
      - name: helloworld-python
        image: kum18/helloworld-python:v1
        ports:
        - containerPort: 8080
