name: docker-build-push_CI-pipline
run-name: ${{github.actor}}
on: push
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1.5. Scan for hardcoded secrets using Gitleaks
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. Lint Dockerfile with Hadolint
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: sample/Dockerfile
          ignore: DL4000,DL3020
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PASS }}
          #updated the password in variable
          
      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t kum18/helloworld-python:v1 -f sample/Dockerfile .
      # diagnostic outpu
      - name: Verify Docker login
        run: docker info

      # 5. Push Docker image
      - name: Push Docker image
        run: docker push kum18/helloworld-python:v1        
      
      # 6. Run the container
      - name: Run the container
        run: docker run --name helloworld-demo-python -itd -p 8080:8080 kum18/helloworld-python:v1

      # 7. View the image
      - name: View the image
        run: docker ps

  k8s-implementation:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloworld-python-deployment
            labels:
              app: helloworld-python
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: helloworld-python
            template:
              metadata:
                labels:
                  app: helloworld-python
              spec:
                automountServiceAccountToken: false
                containers:
                - name: helloworld-python
                  image: kum18/helloworld-python:v1
                  ports:
                  - containerPort: 8080
                  resources:
                    limits:
                      memory: "256Mi"
                    requests:
                      memory: "128Mi"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: helloworld-python-service
          spec:
            type: NodePort
            selector:
              app: helloworld-python
            ports:
              - port: 8080
                targetPort: 8080
                nodePort: 30080
          EOF
